language: node_js
node_js:
- lts/*
- v9
- v8
- v6
install: true
script:
- export root=$(pwd)
# test old
- mkdir /tmp/yo
- cd /tmp/yo
- npm i -g add yo generator-daggerok-fatjar
- echo old-version | yo daggerok-fatjar
# test new
- cd ${root}
- npm i
- npm link
- cd /tmp/yo
- echo new-version | yo daggerok-fatjar
