service:
- docker
sudo: required
group: travis_lts
env:
  global:
    TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
before_script:
- sudo apt udate -y || true
- sudo apt install -y --no-install-recommends curl jq libxml2-utils docker-ce python-pip
- sudo pip install docker-compose httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
script:
- ./gradlew
- java -jar ./build/libs/*-all.jar
#
- ./gradlew clean installDist
- ./build/install/<%= projectDirectory %>/bin/<%= projectDirectory %>
#
- ./gradlew clean distZip
- unzip -o ./build/distributions/<%= projectDirectory %>-0.0.1.zip -d /tmp
- bash /tmp/<%= projectDirectory %>-0.0.1/bin/<%= projectDirectory %>
#
- ./gradlew clean build composeUp
- ./gradlew composeDown
#
- ./mvnw clean package
- java -jar target/*-all.jar
#
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
